# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e6f23eb4-cadc-4e36-ae08-91266dbe3a6f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e6f23eb4-cadc-4e36-ae08-91266dbe3a6f".device = "/dev/disk/by-uuid/e6f23eb4-cadc-4e36-ae08-91266dbe3a6f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/655C-0452";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-c8f361f5-6bae-49e3-aa6e-24df9dc3620b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c8f361f5-6bae-49e3-aa6e-24df9dc3620b".device = "/dev/disk/by-uuid/c8f361f5-6bae-49e3-aa6e-24df9dc3620b";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-e7c3b402-f2b5-4f61-9eeb-d2f9172ad145";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e7c3b402-f2b5-4f61-9eeb-d2f9172ad145".device = "/dev/disk/by-uuid/e7c3b402-f2b5-4f61-9eeb-d2f9172ad145";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c8d096e9-11ac-4d43-b336-246c72218e6f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
